version: '3.7'

services:
  mirror-apt:
    restart: always
    image: apt-mirror:dev
    container_name: apt-mirror
    volumes: 
      - /home/mario/repo/mirror/:/var/spool/apt-mirror/:rw
    command: ["/bin/bash", "-c", "apt-mirror"]
    networks:
      - mirror
  
  nginx:
    restart: always
    image: nginx-mirror:latest
    container_name: nginx-mirror
    volumes:
      - /home/mario/repo/nginx/:/etc/nginx/nginx.d:Z
      - /home/mario/repo/mirror/mirror/:/var/spool/apt-mirror/mirror:rw
    ports:
        - 80:80
        - 443:443
    networks:
      - mirror

  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - /home/mario/repo/registry/:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - mirror
  
networks:
  mirror:
    # external: true
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/16

