FROM nginx:alpine

LABEL VERSION="1.0" NAME="MARIO TANI"

WORKDIR /home/

RUN apk add --no-cache bash nano

COPY ./nginx.conf /etc/nginx/nginx.d/
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]