version: '3.7'

services:
  mirror-apt:
    restart: always
    image: apt-mirror:dev
    container_name: apt-mirror
    volumes: 
      - /home/mario/repo/mirror/:/var/spool/apt-mirror/:rw
    command: ["/bin/bash", "-c", "apt-mirror"]
    networks:
      - mirror
  
  nginx:
    restart: always
    image: nginx-mirror:latest
    container_name: nginx-mirror
    volumes:
      - /home/mario/repo/nginx/:/etc/nginx/nginx.d:Z
      - /home/mario/repo/mirror/mirror/:/var/spool/apt-mirror/mirror:rw
    ports:
        - 80:80
        - 443:443
    networks:
      - mirror

  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - /home/mario/repo/registry/:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - mirror

  portainer_agent:
    container_name: portainer-agent
    image: portainer/agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - mirror

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes: 
      - /home/mario/repo/portainer
    networks:
      - mirror
  
networks:
  mirror:
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/16

