version: '3.7'

services:
  mirror-apt:
    # restart: always
    image: apt-mirror:latest
    # container_name: apt-mirror
    volumes: 
      - ./volume/mirror/:/var/spool/apt-mirror/:rw
    command: ["/bin/bash", "-c", "apt-mirror"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 60s   
    networks:
      - mirror
  
  nginx:
    # restart: always
    image: nginx-mirror:latest
    # container_name: nginx-mirror
    volumes:
      - ./volume/nginx/:/etc/nginx/nginx.d:rw
      - ./volume/mirror/:/var/spool/apt-mirror/:rw
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 60s 
    ports:
        - 80:80
        - 443:443
    networks:
      - mirror
  
networks:
  mirror:

